volumes:
    postgres-data:
    redis-data:

networks:
    frontend:
    backend:

services:
  # nginx
  proxy:
    image: nginx:latest
    ports:
      - "8587:80"
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
      - backend

  # php
  app_ssap:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: ssapweb:v1
    volumes:
      - ./:/var/www/app
    networks:
      - backend
    command: ["sh", "-c", "php-fpm & php artisan schedule:work"]

  # postgresql avec postgis
  postgres:
    image: postgis/postgis:17-3.5
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: userssap
      POSTGRES_DB: ssapbd
      POSTGRES_PASSWORD: mpssapuser
      PGDATA: /var/lib/postgresql/data
    networks:
      - backend

  # redis
  redis:
    image: redis:latest
    sysctls:
      net.core.somaxconn: '511'
    ports:
      - "6393:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend
  npm:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel_npm
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    entrypoint: ["npm", "run", "dev"]
    networks:
      - backend
